title: Duino-Based Learning (DBL)
# author: Acknowledgements
# author: ETSEIB & MathWorks
logo: logo_UPC_MW_whiteBorder2.png

description:  This work has been partially founded by the Spanish 
              national projects MICAPEM (ref. DPI2015-69286-C3-2-R, MINECO/FEDER),
              DPI2017-85404-P and the donation of Mathworks UPC-I-01523.
  
# social links
github_username: DuinoBasedLearning
# youtube_username: watch?v=Z4iJBV6mO18&list=PLObyMFIwX1RlJYZZU_TxDiGUW8sSM1lm-
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

theme: minima
encoding: UTF-8
